apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flinkdep-questionario-mifid-svil
spec:
  image: docker.io/fdaluisio/fd-questionario-mifid-pf-pg:v1
  flinkVersion: "v1_18"
  flinkConfiguration:
    license.use: EventAutomationNonProduction
    license.license: L-HRZF-DWHH7A
    license.accept: 'true'
    high-availability.type: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory
    high-availability.storageDir: 'file:///opt/flink/volume/flink-ha'
    restart-strategy: failure-rate
    restart-strategy.failure-rate.max-failures-per-interval: '10'
    restart-strategy.failure-rate.failure-rate-interval: 10 min
    restart-strategy.failure-rate.delay: 30 s
    execution.checkpointing.interval: '5000'
    execution.checkpointing.unaligned: 'false'
    state.backend.type: rocksdb
    state.backend.incremental: 'true'
    state.backend.rocksdb.use-bloom-filter: 'true'
    state.checkpoints.dir: 'file:///opt/flink/volume/flink-cp'
    state.checkpoints.num-retained: '3'
    state.savepoints.dir: 'file:///opt/flink/volume/flink-sp'
    taskmanager.numberOfTaskSlots: '10'
    table.exec.source.idle-timeout: 30 s
    # security.ssl.enabled: 'true'  
    # security.ssl.truststore: /opt/flink/tls-cert/truststore.jks
    # security.ssl.truststore-password: <jks-password>
    # security.ssl.keystore: /opt/flink/tls-cert/keystore.jks
    # security.ssl.keystore-password: <jks-password>
    # security.ssl.key-password: <jks-password>
    # kubernetes.secrets: '<jks-secret>:/opt/flink/tls-cert'
  serviceAccount: flink
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-template
    spec:
      containers:
        - name: flink-main-container
          volumeMounts:
            - name: flink-logs
              mountPath: /opt/flink/log
            - name: flink-volume
              mountPath: /opt/flink/volume
      volumes:
        - name: flink-logs
          emptyDir: {}
        - name: flink-volume
          persistentVolumeClaim:
            claimName: ibm-flink-pvc
  jobManager:
    replicas: 1
    resource:
      memory: 1024m
      cpu: 0.5
  taskManager:
    resource:
      memory: 1024m
      cpu: 0.5
  job:
    jarURI: local:///opt/flink/usrlib/sql-runner.jar
    args: ["/opt/flink/usrlib/sql-scripts/QUESTINOARIO_MIFID_PF_PG.sql"]
    parallelism: 1
    state: running
    upgradeMode: savepoint
    resource:
      memory: 2048m
      cpu: 1
  mode: native

