# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  finalizers:
  - flinkdeployments.flink.apache.org/finalizer
  labels:
    app.kubernetes.io/instance: dev-flink
  name: flinkdep-session-cluster-svil
  namespace: myproject
spec:
  flinkConfiguration:
    execution.checkpointing.interval: "5000"
    license.accept: "true"
    license.license: L-HRZF-DWHH7A
    license.use: EventAutomationNonProduction
    state.backend.type: rocksdb
    state.checkpoints.num-retained: "3"
    table.exec.source.idle-timeout: 30 s
    taskmanager.numberOfTaskSlots: "2"
    state.savepoints.dir: file:///opt/flink/flink-sp/
    state.checkpoints.dir: file:///opt/flink/flink-cp/
  flinkVersion: v1_18
  job:
    parallelism: 2
    autoSavepointSeconds: 300
    upgradeMode: savepoint
    state: running
  image: icr.io/cpopen/ibm-eventautomation-flink/ibm-eventautomation-flink@sha256:4904832f776e6510189f95e53fa27d91cec73855c4b871a687918ea3c59e90c2
  jobManager:
    replicas: 1
    resource:
      cpu: 0.5
      memory: 1024m
  mode: native
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-template
      containers:
      - name: flink-main-container
        volumeMounts:
        - mountPath: /opt/flink/log
          name: flink-logs
        - mountPath: /opt/flink/flink-sp
          name: flink-sp
        - mountPath: /opt/flink/flink-cp
          name: flink-cp
      volumes:
      - emptyDir: {}
        name: flink-logs
      - emptyDir: {}
        name: flink-sp
      - emptyDir: {}
        name: flink-cp
  serviceAccount: flink
  taskManager:
    resource:
      cpu: 0.5
      memory: 1024m
