apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flinkdep-session-cluster-svil
spec:
  flinkConfiguration:
    license.use: EventAutomationNonProduction
    license.license: L-HRZF-DWHH7A
    license.accept: 'true'
    execution.checkpointing.interval: '5000'
    state.backend.type: rocksdb
    state.checkpoints.num-retained: '3'
    taskmanager.numberOfTaskSlots: '4'
    table.exec.source.idle-timeout: 30 s
  serviceAccount: flink
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-template
    spec:
      containers:
        - name: flink-main-container
          volumeMounts:
            - name: flink-logs
              mountPath: /opt/flink/log
      volumes:
        - name: flink-logs
          emptyDir: {}
  jobManager:
    resource:
      memory: 1024m
      cpu: 0.5
  taskManager:
    resource:
      memory: 2048m
      cpu: 1
  mode: native
