apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
    finalizers:
        - flinkdeployments.flink.apache.org/finalizer
    name: flinkdep-svil
    namespace: myproject
spec:
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: '2'
    state.checkpoints.num-retained: '1'
    execution.checkpointing.interval: '5000'
    state.backend.type: rocksdb
    license.license: L-HRZF-DWHH7A
    license.accept: 'true'
    json.ignore-parse-errors: 'true'
    license.use: EventAutomationNonProduction
    table.exec.source.idle-timeout: 30 s
  flinkVersion: v1_18
  image: 'icr.io/cpopen/ibm-eventautomation-flink/ibm-eventautomation-flink@sha256:132593d0d270d337fb7c29b6d9afdeeaf54e1fdb826e8ff0124faee91de121d8'
  jobManager:
    replicas: 1
    resource:
      cpu: 0.5
      memory: 1024m
  mode: native
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-template
    spec:
      containers:
        - name: flink-main-container
          volumeMounts:
            - mountPath: /opt/flink/log
              name: flink-logs
      volumes:
        - emptyDir: {}
          name: flink-logs
  serviceAccount: flink
  taskManager:
    resource:
      cpu: 1
      memory: 2048m
