apiVersion: events.ibm.com/v1beta1
kind: EventProcessing
metadata:
  # name: quick-start-ep  # <- based on ibm-eventprocessing operator source example 
  name: eventprocessing-svil
  namespace: myproject
spec:
  authoring:
    authConfig:
      authType: LOCAL
    storage:
      type: persistent-claim
      existingClaimName: eventprocessing-pvc
  license:
    accept: true
    license: L-HRZF-DWHH7A
    use: EventAutomationNonProduction
  flink:
    endpoint: 'flinkdep-cluster-savepoint-svil-rest:8081'
    # tls:   # <- Add in prod/valid env
    #   secretKeyRef:
    #     key: <key-contain-password-value>
    #     name: <flink-jks-password-secret>
    #   secretName: <flink-jks-secret>
 
