apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-flink
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: 'in-cluster'
    namespace: myproject
  source:
    path: flink-instance/overlay/dev/
    repoURL: 'https://github.com/fdaluisio/apache-flink.git'
    targetRevision: HEAD
    kustomize: {}
      # components:
      #   - overlay/dev/
  syncPolicy: {}
